### ISSUE TITLE
Charts of different repos are mixed

### ISSUE THREAD

**Issue by ckotzbauer** [fabmation-gmbh/helm-whatup#21]
Hi,
thanks for developing this fork until the feature is merged to core!

I found a bug, when a chart with the same name is part of multiple added repos. The logic seems to "mix" the charts and shows a update for a installed release where no never version is available.

Example:

I have the following repos configured:
```
$ helm repo list
elastic       https://helm.elastic.co
stable      	https://kubernetes-charts.storage.googleapis.com
bitnami     	https://charts.bitnami.com/bitnami
```

I installed the "minio" chart from the "bitnami" repo:
```
$ helm list
NAME 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART      	APP VERSION
minio	minio    	2       	2020-01-06 19:15:42.862116066 +0100 CET	deployed	minio-2.2.0	2019.10.12
```

The newest version of this chart in "bitnami" is `2.2.0` as installed. In the "stable" repo the newest version is `5.0.4`.

This plugin shows an update for minio:
```
$ helm whatup
NAME         	NAMESPACE     	INSTALLED VERSION	LATEST VERSION	CHART        
minio        	minio         	2.2.0            	5.0.4         	minio
```

The same happens for the "elasticsearch" chart (installed from elastic-repo, newer version available in bitnami-repo).

Maybe someone can look into it, what is going wrong here. Thanks! :)

**Comment by l0nax** [comment]
First of all: I'm sorry for my late answer.

I can add a flag (which will be enabled by default) to only search in repositories where the Chart was installed. I don't want to completely remove this "feature" because I want also to check if there are other Charts that are newer and then eventually check out if my current repository is deprecated/ not maintained anymore.

**Comment by ckotzbauer** [comment]
@l0nax No problem, thanks for your answer!

Well, that's a good point. The problem is, that the chart versions often not match the app versions. So it is hard to figure out (automatically) if another chart is deprecated or not.
But I think a flag with this default-setting is a good tradeoff :+1:

**Comment by l0nax** [comment]
> The problem is, that the chart versions often not match the app versions.

I don't think that this is a Problem because it intended to be so because they describe different types of Software. The _Chart-Version_ describes the current version of the Helm-Chart and the _App-Version_ describes the current version of the Application which will be served by this Helm-Package.

To figure out automatically if a Chart(-Repository) is deprecated or serves a deprecated version of a helm chart we can check out the `created` parted of the [`index.yaml`](https://helm.sh/docs/topics/chart_repository/#the-index-file) file and then compare all creation-dates and check if a repository is over a specific period (eg. 60 days).

And also - correct me if I'm wrong because I don't remember well - we could also compare the _AppVersion_ of all available charts and mark those repositories as _deprecated_ which serves applications which are older than _1 Major_ or _1 minor_ release.

But I don't know if this will consume more considerably more computing power which will slow down the Plugin hugely, is than Caching a good way to go?

**Comment by ckotzbauer** [comment]
Maybe something like this would be good:
```
$ helm whatup
NAME         	NAMESPACE     	INSTALLED VERSION	LATEST VERSION	APP VERSION    CHART   UPDATED                                   REPOSITORY
minio        	minio         	2.2.0            	2.2.1         	2019.10.12     minio   2020-01-06 19:15:42.862116066 +0100 CET   bitnami
minio        	minio         	                  5.0.5           master         minio   2019-10-12 10:36:00.650545046 +0100 CET   stable
```
This would solve the following aspects:
- You see which repository is used for the current installation
- When were the charts published
- Which appVersion they serve (if this is really set correctly)

With the last two points everybody can decide on its own if the chart is maybe deprecated, too old or something else... This prevents us from marking charts as deprecated even if they are not..

From the performance perspective I think (with almost no know-how with Golang) that this should be ok. All data needed for the above comparisons are available in the chart object already and the comparison itself should be fast enough... But I'm not sure about that and I did not check your code in the PR for the "outdated" command for Helm-Core...

If it is too slow, caching is definitely an option.

**Comment by l0nax** [comment]
I think instead of "merging" that Information where we have only one repository which serves the Chart and those where we have multiple Chart repositories we should create an output like this:

```
NAME            NAMESPACE       INSTALLED VERSION       LATEST VERSION  CHART
xyz             xyz             2.2.0                   5.0.4           xyz


NOTE: We have found some deprecated Charts in some of your Repositories.
      Check if your current Chart-Repositories is deprecated/ not getting updated
      and consider to migrate to an updated Chart-Repository.

-----
NAME                    minio
NAMESPACE               minio
INSTALLED VERSION       2.2.1
APP VERSION             2019.10.12
LATEST APP VERSION      2020.01.10
CHART NAME              minio
(CURRENT) REPOSITORY    bitnami

REPOSITORY      AVAILABLE VERSION       APP VERSION     UPDATED
bitnami         2.2.1                   2019.10.12      2020-01-06 19:15:42.862116066 +0100 CET
stable          5.0.5                   master          2019-10-12 10:36:00.650545046 +0100 CET
-----
NAME                    asd
NAMESPACE               asd
INSTALLED VERSION       5.7.0
APP VERSION             2019.09.12
LATEST APP VERSION      2019.12.30
CHART NAME              asd-stable
(CURRENT) REPOSITORY    incubator

REPOSITORY      AVAILABLE VERSION       APP VERSION     UPDATED
incubator       1.0.1                   2019.09.12      2020-01-06 19:15:42.862116066 +0100 CET
stable          5.7.0                   2019.12.12      2019-12-12 10:36:00.650545046 +0100 CET
-----
```

And combining this with a Config/ ENV vars to disable it completely (or even better: showing only a hint) would be a better idea.

What do you think about this @code-chris ?

**Comment by ckotzbauer** [comment]
I like this idea too. All charts where the user only have to update are displayed at the top and others which may require additional actions have a more detailed output.
This should be configurable with ENVs or flags, yes.... :+1:

**Comment by l0nax** [comment]
Ok, I will work on it ASAP.

**Comment by l0nax** [comment]
I'm now starting implementing this Feature/ solving the Problem :D

**Comment by l0nax** [comment]
Current branch: https://github.com/fabmation-gmbh/helm-whatup/tree/feature/21_charts-of-different-repos-are-mixed

**Comment by l0nax** [comment]
Hey @ckotzbauer, sorry for taking so long to implement it, but I now found some time and the first alpha "version" is ready to be tested.

Would it be able for you to pull (and checkout) the `feature/21_charts-of-different-repos-are-mixed` repository, build, install, and test it?

Currently, the output does looks like:
```
NAME     	NAMESPACE	INSTALLED VERSION	LATEST VERSION	CHART 
gitlab-ee	gitlab   	4.2.0            	4.2.3         	gitlab


----
NAME                    plantuml
NAMESPACE               gitlab
INSTALLED VERSION       0.1.1

REPOSITORY	AVAILABLE VERSION	APP VERSION	UPDATED                                
gitlab    	0.1.13           	1.0        	2020-07-07 13:10:02.217893237 +0000 UTC
fab-stable	0.1.1            	v1.2020.14 	2020-07-30 11:35:29.468463 +0000 UTC   
```

**Comment by ckotzbauer** [comment]
@l0nax  I'll give it a try yes! 😅

**Comment by ckotzbauer** [comment]
@l0nax I just tested it and it looks good. Thank you! :+1:

**Comment by l0nax** [comment]
@ckotzbauer Does the feature work for you? If so, can we then close this issue?

**Comment by ckotzbauer** [comment]
I think we can close this
