### ISSUE TITLE
Output formatting

### ISSUE THREAD

**Issue by stevehipwell** [fabmation-gmbh/helm-whatup#37]
The current output formatting for charts with multiple repos isn't particularly easy to grok due to the separator only being three characters `---` and the blank line in the middle of the block appearing to be the separator. If the separator could be extended in length to at least the length of the header that would be great and it might be worth considering a line break after each block.

It would also make the multi repo output easier to scan and act on if there was a visual marker to show which chart is currently installed.

Finally I'm sure you're aware but the help command refers to `outdated` not `whatup`.

FYI I really appreciate that you've kept this plugin working as I feel an outdated command should be part of core Helm (it's a fundamental package manager feature).

**Comment by l0nax** [comment]
I've implemented the longer separator _and_ fixed the typo.

And the highlighted installed version, in the table, will be implemented soon.

**Comment by stevehipwell** [comment]
Thanks @l0nax that's great!

**Comment by l0nax** [comment]
I already tried to implement the functionality to show the user from which Chart repository the release has been installed.

But this is, out of the box, not possible.

The installed _releases_ are returned as [`*release.Release`](https://pkg.go.dev/helm.sh/helm/v3/pkg/release#Release) and this struct does not have a field where it is possible to find out which Chart exactly has been installed.
The [`*chart.Chart`](https://pkg.go.dev/helm.sh/helm/v3@v3.5.0/pkg/chart#Chart) struct does not provide any information about the repository.

I see only one way to implement this functionality:
1. Create a hash of the release information (`Chart`, `Manifest`, and `Hooks` from [`*release.Release`](https://pkg.go.dev/helm.sh/helm/v3/pkg/release#Release))
2. Search for a repository with the _**same** Chart version_ and _App Version_
3. Generate the hash for all repositories serving this chart by using `Config`, and `Labels` from [`*release.Release`](https://pkg.go.dev/helm.sh/helm/v3/pkg/release#Release)
4. Compare all generated hashes to find the repository

But this is really computing-intensive, i.e. execute `helm template` and measure the execution time. For the _GitLab EE Chart_ it takes _6.791 seconds_. This would take a lot of time if you have many charts installed that are served by many repositories, i.e., if you have the `stable` and `bitnami` Chart repository added to your repo list.

Those generated hashes can be cached, yes, but it would take a lot of time if the deployed Chart changes.

I will first work on the other issues you've opened, and then I will try to implement this feature – but it will not be enabled by default.

I'm open to other ideas to implement this functionality because it would improve usability.

**Comment by stevehipwell** [comment]
I'd settle for a fuzzy match on `version` and `appVersion` where all possible charts are starred as a MVP; usually this would be good enough I think. Would this make the process easier?

**Comment by l0nax** [comment]
It could be that multiple charts do have the same _Chart and App Version_, which will then result in multiple Chart repositories marked as "installation source".

**Comment by stevehipwell** [comment]
I think it would be a step in the right direction even if not a perfect solution.

**Comment by l0nax** [comment]
I've implemented it as described by you (https://github.com/fabmation-gmbh/helm-whatup/issues/37#issuecomment-768288288) and it looks like this:

![Screenshot_20210127_190803](https://user-images.githubusercontent.com/29659953/106034395-2b8da080-60d3-11eb-8ee7-ea66a74fc17b.png)


Currently, this feature is marked as _beta_ and can be enabled by adding the `--color` flag to the command **OR** by exporting `HELM_WHATUP_BETA_FEATURES=true` which will cause that all beta features (currently only the coloring) will be enabled.

**Comment by stevehipwell** [comment]
This looks great!!

**Comment by l0nax** [comment]
The changes have been merged onto `develop`.

**Comment by l0nax** [comment]
I will create a new release so you can test it.

**Comment by l0nax** [comment]
@stevehipwell Version [v0.5.0](https://github.com/fabmation-gmbh/helm-whatup/releases/tag/v0.5.0) has been released. Can you please update the plugin and test if everything works fine for you?

**Comment by stevehipwell** [comment]
Thanks @l0nax I'll give this a try in the morning.
